<div class="footer-links">
  <div class="block my-account">
    <h4><?= __('My account') ?></h4>
    <ul>
        <li><a href="#" title="<?= __('Personal data') ?>"><?= __('Personal data') ?></a></li>
        <li><a href="#" title="<?= __('Change Password') ?>"><?= __('Change Password') ?></a></li>
        <li><a href="#" title="<?= __('My requests') ?>"><?= __('My requests') ?></a></li>
        <li><a href="#" title="<?= __('Delivery address') ?>"><?= __('Delivery address') ?></a></li>
    </ul>
  </div>
  <div class="block institutional">
    <h4><?= __('Institutional') ?></h4>
    <ul>
        <li><a href="#" title="<?= __('About Us') ?>"><?= __('About Us') ?></a></li>
        <li><a href="#" title="<?= __('Our products') ?>"><?= __('Our products') ?></a></li>
        <li><a href="#" title="<?= __('Work with us') ?>"><?= __('Work with us') ?></a></li>
        <li><a href="#" title="<?= __('Discover our store') ?>"><?= __('Discover our store') ?></a></li>
    </ul>
  </div>
  <div class="block contact">
    <h4><?= __('Contact') ?></h4>
    <div class="content">
        <div class="contact-us">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('image/infohq/fa-whatsapp.svg'))?>" alt="whatsapp">
            <span title="<?= __('Whatsapp') ?>">11 9 1234-5678</span>
        </div>
        <div class="contact-us">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('image/infohq/fa-map-marker.svg'))?>" alt="<?= __('Localization') ?>">
            <span title="<?= __('Localization') ?>">R. Bem Tranquila n°100</span>
        </div>
        <div class="contact-us">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('image/infohq/fa-envelope.svg'))?>" alt="email">
            <span title="<?= __('Email') ?>">infohq.store@gmail.com</span>
        </div>
    </div>
  </div>
  <div class="block doubts">
    <h4><?= __('Doubts') ?></h4>
    <ul>
        <li><a href="#" title="<?= __('Shipping methods') ?>"><?= __('Shipping methods') ?></a></li>
        <li><a href="#" title="<?= __('Payment methods') ?>"><?= __('Payment methods') ?></a></li>
        <li><a href="#" title="<?= __('Guarantee and security') ?>"><?= __('Guarantee and security') ?></a></li>
        <li><a href="#" title="<?= __('Budgets') ?>"><?= __('Budgets') ?></a></li>
    </ul>
  </div>
</div>
